CREATE TABLE [DW].[FactOBV](
	[NmdID] [int] NULL,
	[DteID] [int] NULL,
	[OBV] [decimal](38, 0) NULL
) ON [PRIMARY]
GO

ALTER TABLE [DW].[FactOBV]  WITH CHECK ADD  CONSTRAINT [FK_FactOBV_DimDate] FOREIGN KEY([DteID])
REFERENCES [DW].[DimDate] ([ID])
GO

ALTER TABLE [DW].[FactOBV] CHECK CONSTRAINT [FK_FactOBV_DimDate]
GO

ALTER TABLE [DW].[FactOBV]  WITH CHECK ADD  CONSTRAINT [FK_FactOBV_DimNmds] FOREIGN KEY([NmdID])
REFERENCES [DW].[DimNmds] ([NmdID])
GO

ALTER TABLE [DW].[FactOBV] CHECK CONSTRAINT [FK_FactOBV_DimNmds]
GO
