CREATE TABLE [DW].[FactNmds] (
    [ID]        INT             IDENTITY (1, 1) NOT NULL,
    [NmdID]     INT             NOT NULL,
    [DteID]     INT             NULL,
    [OpenPrc]   DECIMAL (26, 2) NULL,
    [MaxPrc]    DECIMAL (26, 2) NULL,
    [MinPrc]    DECIMAL (26, 2) NULL,
    [ClosePrc]  DECIMAL (26, 2) NULL,
    [Vol]       DECIMAL (38, 2) NULL,
    [TrdWrth]   DECIMAL (26)    NULL,
    [TrdCnt]    DECIMAL (26, 2) NULL,
    [GrpID]     INT             NULL,
    [Lst_Prc]   DECIMAL (26, 2) NULL,
    [Lst_Chng]  DECIMAL (26, 2) NULL,
    [Lst_Prcnt] DECIMAL (10, 2) NULL,
    [EPS]       DECIMAL (10, 2) NULL,
    [P/E]       DECIMAL (10, 2) NULL,
    [Buy_Cnt]   DECIMAL (10, 2) NULL,
    [Buy_Vol]   DECIMAL (26, 2) NULL,
    [Buy_Prc]   DECIMAL (26, 2) NULL,
    [Sell_Cnt]  DECIMAL (10, 2) NULL,
    [Sell_Vol]  DECIMAL (26, 2) NULL,
    [Sell_Prc]  DECIMAL (26, 2) NULL,
    [Fin_Prcnt] FLOAT (53)      NULL,
    [RegDte]    DATETIME        DEFAULT (getdate()) NULL,
    [MinLmtPrc] INT             NULL,
    [MaxLmtPrc] INT             NULL,
    CONSTRAINT [FK_FactNmds_DimDate] FOREIGN KEY ([DteID]) REFERENCES [DW].[DimDate] ([ID]),
    CONSTRAINT [FK_FactNmds_DimGrps] FOREIGN KEY ([GrpID]) REFERENCES [DW].[DimGrps] ([GrpID]),
    CONSTRAINT [FK_FactNmds_DimNmds] FOREIGN KEY ([NmdID]) REFERENCES [DW].[DimNmds] ([NmdID])
);

